import React from 'react';
import {
  FiGrid,
  FiUsers,
  FiLayers,
  FiBriefcase,
  FiFolder,
  FiCheckSquare,
  FiTrello,
  FiCoffee,
  FiFileText,
  FiCalendar,
  FiBarChart2,
  FiActivity,
  FiSettings,
  FiSearch,
  FiBell,
  FiPlus,
  FiEdit3,
  FiTrash2,
  FiX,
  FiCheck,
  FiChevronDown,
  FiChevronRight,
  FiUser,
  FiArrowLeft,
  FiAlertCircle,
  FiDownload,
  FiUploadCloud,
  FiMoreVertical,
  FiClock,
  FiMenu,
  FiLock,
  FiEye,
  FiEyeOff
} from 'react-icons/fi';

export const Icons = {
  Dashboard: (props) => <FiGrid {...props} />,
  Employees: (props) => <FiUsers {...props} />,
  Departments: (props) => <FiLayers {...props} />,
  Teams: (props) => <FiBriefcase {...props} />,
  Projects: (props) => <FiFolder {...props} />,
  Tasks: (props) => <FiCheckSquare {...props} />,
  Kanban: (props) => <FiTrello {...props} />,
  Leaves: (props) => <FiCoffee {...props} />,
  Announcements: (props) => <FiBell {...props} />,
  Documents: (props) => <FiFileText {...props} />,
  Calendar: (props) => <FiCalendar {...props} />,
  Reports: (props) => <FiBarChart2 {...props} />,
  ActivityLogs: (props) => <FiActivity {...props} />,
  Settings: (props) => <FiSettings {...props} />,
  Search: (props) => <FiSearch {...props} />,
  Bell: (props) => <FiBell {...props} />,
  Plus: (props) => <FiPlus {...props} />,
  Edit: (props) => <FiEdit3 {...props} />,
  Trash: (props) => <FiTrash2 {...props} />,
  Close: (props) => <FiX {...props} />,
  Check: (props) => <FiCheck {...props} />,
  ChevronDown: (props) => <FiChevronDown {...props} />,
  ChevronRight: (props) => <FiChevronRight {...props} />,
  User: (props) => <FiUser {...props} />,
  ArrowLeft: (props) => <FiArrowLeft {...props} />,
  Alert: (props) => <FiAlertCircle {...props} />,
  Download: (props) => <FiDownload {...props} />,
  Upload: (props) => <FiUploadCloud {...props} />,
  More: (props) => <FiMoreVertical {...props} />,
  Clock: (props) => <FiClock {...props} />,
  Menu: (props) => <FiMenu {...props} />,
  Lock: (props) => <FiLock {...props} />,
  Eye: (props) => <FiEye {...props} />,
  EyeOff: (props) => <FiEyeOff {...props} />
};

export default Icons;
